### ISSUE TITLE
Verticies are all crazy

### ISSUE THREAD

**Issue by formicsapien** [Petethegoat/smdConverter#2]
I just decompiled the HD version of the pistol MDL that ships with HL using crowbar.  I opened it in blender and fixed the UV.  Then I exported everything, and used your program for fixing stuff.  I ran all the meshes and animations through (and had to tweak smds and the qc file to make it compatible with studiomdl).  I got it working in game, but the gun is all crazy wonkey.  I think the bones, and maybe not the virticies, are messed up.
 
And btw, thanks for making an awesome free alternative!

**Comment by Petethegoat** [comment]
It's been a long time since I used this for anything, but I can try and take a look into it. Can you upload the converted smd?

**Comment by formicsapien** [comment]
The problem ended up being when I export using Steam Blender exporter when I export the animations and the models together.  I exported them separately and now there's no problem.  Thanks though, you can close the issue.

**Comment by Petethegoat** [comment]
Ah, glad you got it working. Nice to see this thing getting some use.
